[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests",
]

[tool.mypy]
python_version = "3.8"
show_column_numbers = true
check_untyped_defs = true
warn_unused_configs = true
ignore_missing_imports = true
follow_imports = "normal"
namespace_packages = true
explicit_package_bases = true
mypy_path = "./src"
files = "./src"